# Generated by Django 4.2.2 on 2023-08-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('nadkategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eshop.kategorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Znacka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('popis', models.TextField(blank=True, max_length=1000)),
                ('aktualni_cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mnozstvi', models.PositiveIntegerField(default=0)),
                ('vlastnosti', models.JSONField(blank=True, default=dict)),
                ('kategorie', models.ManyToManyField(blank=True, to='eshop.kategorie')),
                ('znacka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eshop.znacka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plati_od', models.DateField()),
                ('plati_do', models.DateField()),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eshop.produkt')),
            ],
        ),
    ]
