# Generated by Django 4.2.2 on 2023-11-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('old', models.CharField(max_length=3)),
                ('info', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movie_photos/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmy.country')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmy.genre')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmy.type')),
            ],
        ),
    ]
